### ISSUE TITLE
Lat Long associated with 77035 is incorrect

### ISSUE THREAD

**Issue by kautif** [millbj92/US-Zip-Codes-JSON#6]
If you do a lookup on the lat long of 77035, it actually gives you the zip code of 77018. 
Lat: 29.83399
Long: -95.434241

**Comment by millbj92** [comment]
hmm, yeah it seems that 77035 and 77018 both have the same exact lat/long. As I don't know the area/zips very well (not from TX), would you be willing to submit a quick PR? If not I'm sure I can figure it out. Thanks!
